- README.md
Have a look at the "rich diff" (document icon in the header of the README.md diff view) instead of the code diff to see how the generated HTML changes.
> Fix ordered list formatting in README.md

- concurrentqueue.h
```cpp
-#if defined(__APPLE__) || defined(__clang__) || !defined(__GNUC__) || __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8)
+#if defined(__clang__) || !defined(__GNUC__) || __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8)
```
ref #14
> __clang__ is enough even when compiling with "gcc" on Mac OS X

- concurrentqueue.h
Just a small patch to initialise a couple of vars that were left out of the init. lists. Largely to silence analysis tools. =)
> Initialise pointers in ctors

- tests/fuzztests/fuzztests.cpp
Compiling the test suite with Visual Studio 2015 Update 1 results in two compiler errors:
- One in `boost::lockfree::queue<T>`'s constructor, which is fixable by updating from Boost 1.55 to a more recent version (it works fine with 1.60 in my tests). This PR does not include an updated Boost.
- One in [`tests/fuzztests.cpp`](https://github.com/cameron314/concurrentqueue/blob/5ec729e63560a01f3dadc1f58d07b36bbd76a373/tests/fuzztests/fuzztests.cpp#L675-L677):
```
if (g_prev_sigsegv.load(std::memory_order_relaxed) != nullptr) {
g_prev_sigsegv(signal);
}
```
This is a subtle one; `std::atomic<signal_handler_t>` has two implicit conversion operators—[`operator signal_handler_t() const` and `operator signal_handler_t() const volatile`](http://en.cppreference.com/w/cpp/atomic/atomic/operator_T). …
> Prevent surrogate call ambiguity

- concurrentqueue.h
TARGET_OS_IPHONE (used in concurrentqueue.h) is defined in
TargetConditionals.h
> Include TargetConditionals.h for Apple platforms.

- .gitignore
- build/xcode/Info.plist
- build/xcode/concurrentqueue.xcodeproj/project.pbxproj
- build/xcode/concurrentqueue.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- build/xcode/concurrentqueue.xcodeproj/xcshareddata/xcschemes/concurrentqueue-unittests-ios.xcscheme
- build/xcode/main_ios.mm
- tests/corealgos.h
- tests/unittests/unittests.cpp
Added a minimal Xcode project with a iOS Application target that
provides a minimal UIApplicationDelegate that can host / run the unit
tests.
The target is intentionally setup as an "Application"-type target rather
than an XCTest bundle as it is generally easier to run application
targets on device (vs iOS Simulator).
Explicitly enabled build settings:
Release configuration: NDEBUG=1
The commited shared .xcscheme is set to build and tests in Release.
> Support running unit tests on iOS device

- concurrentqueue.h
It seems that clang defines __GNUC__ but doesn't have the same problems as gcc, so I added this extra check
> fix the ifdef for max_align_t for use with clang

- benchmarks/benchmarks.cpp
Added code to generate benchmarks for moody::BlockingConcurrentQueue.  While statistics are available for moody::ConcurrentQueue, they were absent for moody::BlockingConcurrentQueue.
Please check benchmark parameters during code review.  On a side note, I note that the Makefile uses -O3 instead of -O2.  Slightly controversial. :)
> Added benchmarking for moody::BlockingConcurrentQueue.

- concurrentqueue.h
The `max_align_t` issue is in libstdc++ rather than GCC itself. This problem surfaces when
the library is used in clang / libstdc++ setup rather than clang / libc++. Here we simply check
for `__GLIBCXX__` rather than `__GNUC__`.
> Updated the `max_align_t` workaround to look for libstdc++ instead of GCC.

- blockingconcurrentqueue.h
Current code assumes that any value other than KERN_OPERATION_TIMED_OUT i
ndicates signal from another thread. 
This assumption is false, as other return values include interrupt,
e.g. from debugger.
This leads to infinite loop here: 
https://github.com/cameron314/concurrentqueue/blob/master/blockingconcurrentqueue.h#L817
> Fix infinite loop in blockingconcurrentqueue on OS X

- concurrentqueue.h
For some reason the concurrentqueue.h file had a BOM file header and this prevent `#pragma once` to work correctly with gcc and precompiled headers (related issue is https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=56549), leading to obscure errors like
```
In file included from main.cpp:2:0:
/usr/include/concurrentqueue/concurrentqueue.h:49:40: error: redefinition of ‘struct moodycamel::details::thread_id_converter<thread_id_t>’
template<typename thread_id_t> struct thread_id_converter {
^~~~~~~~~~~~~~~~~~~
In file included from pch.h:2:0:
/usr/include/concurrentqueue/concurrentqueue.h:49:40: note: previous definition of ‘struct moodycamel::details::thread_id_converter<thread_id_t>’
template<typename thread_id_t> struct thread_id_converter {
```
> Remove BOM from concurrentqueue.h

- concurrentqueue.h
> suppress clang-tidy warnings with "NOLINT" on use-after-move lines

- concurrentqueue.h
Prevent warnings like MSVC's [C4668](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4668?view=vs-2019)
> Replace #if with #ifdef to prevent undefined internal macros

- concurrentqueue.h
clang tidy has a false positive for line 3360.
> Added nolint line 3360 clang tidy 5.0

- concurrentqueue.h
Fix warning triggered by ```MCDBGQ_USEDEBUGFREELIST``` not being defined.
> Fix GCC -Wundef warning

- concurrentqueue.h
This replaces the `static_assert` preventing super-aligned types from being used with one that prevents types with an alignment greater than their size from being used, sets `Block`'s alignment equal to `T`'s, adds `aligned_malloc` and `aligned_free` to `ConcurrentQueueDefaultTraits`, and adds specializations of `create`, `create_array`, `destroy`, and `destroy_array` for super-aligned types that use them.
> Adding support for super-aligned types

- concurrentqueue.h
Fixes https://github.com/cameron314/concurrentqueue/issues/177
> Fix under-alignment issues

- concurrentqueue.h
I use c++17 [if constexpr] stmt to reduce code size, and fix some MSVC warning in /std:c++latest mode.
> Added c++17 if constexpr to reduce code size and fix MSVC warning

- concurrentqueue.h
This adds a macro MOODYCAMEL_NO_TSAN which can be applied to functions the mis-report TSAN error, e.g. in the face of lock-free programming.  Additionally, I applied it to one function, which made all of my tests run clean under TSAN.  Others can apply the macro to other functions on an as-needed basis.
> Add macro to disable TSAN reporting on a per-function basis

- concurrentqueue.h
Changing the preprocessor check for address sanitizer to match documented method, just like the fix for https://github.com/cameron314/readerwriterqueue/issues/69
> Fixing check for address sanitizer

- concurrentqueue.h
I came across some easy-to-fix warnings which I don't want to turn off in my cmake configuration.
You can trigger those with `clang++ -Wno-c++98-compat -Wno-c++98-compat-pedantic -Weverything`.
> Fixed clang warnings.

- benchmarks/benchmarks.cpp
- benchmarks/dlib/config.h
- benchmarks/dlib/test_for_odr_violations.h
- c_api/concurrentqueue.h
First, in C API for non-win platform some macro was not defined
Second, benchmark didn't compile for two very different reasons.
First reason: some missed symbols, mostly because dlib is a compiled library with extensive checks for versioning and ODR across multiple compilation units. Luckily, that's fixed with its config and one minor bugfix.
Second, the most important: dpipe has no API for copy to queue, only exchange. And that means, you can't exchange counter_t values with int values. And you can't replace all `int`s with `counter_t` for `i` either, because exchange will replace it's value. So, fast way is to copy to some temp and then enqueue it. But that means double copy for every other queues, not good. And special benchmark for that is not good either. So, I changed benchmarks …
> Dpipe and minor C API fix

- concurrentqueue.h
Currently it is not possible to compile with Intel when warnings are turned into errors (`-Werror-all`):
~~~
concurrentqueue.h(38): error #2282: unrecognized GCC pragma
#pragma GCC diagnostic push
^
concurrentqueue.h(39): error #2282: unrecognized GCC pragma
#pragma GCC diagnostic ignored "-Wconversion"
^
concurrentqueue.h(3741): error #2282: unrecognized GCC pragma
#pragma GCC diagnostic pop
~~~
this PR fixes this
> adding wards for Intel compiler

- concurrentqueue.h
I am encountering this case with LLVM's JIT, which is not able to handle thread local relocations as of LLVM 12, even for __thread ; thus use the std::thread API in that case.
> Add an escape hatch when thread-local is not supported

- CMakeLists.txt
- concurrentqueueConfig.cmake.in
Properly export cmake targets in order to consume library in other cmake projects
```cmake
find_package(concurrentqueue REQUIRED)
add_library(test test.cpp)
target_link_libraries(test  PRIVATE  concurrentqueue::concurrentqueue)
```
> Modernize cmake

- README.md
Since it is available through vcpkg, it could be useful for some users to have the doc about how to install and use the library through this channel.
> Add doc for vcpkg installation of the library

- blockingconcurrentqueue.h
- concurrentqueue.h
- tests/unittests/unittests.cpp
This makes it possible to use it in `static_assert`, which is better
than a runtime error.
> Make is_lock_free constexpr.

- concurrentqueue.h
in project i work on, we are warn free, but we have theese warning
`unreachable code line 2909, 2912, 2913`
fixes theese warnings in debug + more logical
> Fix unreachable code warning in Win debug

- concurrentqueue.h
The previous fix to the annoying MSVC warning did not work, as it still triggered when some code instantiated this function. I [reported](https://developercommunity2.visualstudio.com/t/C4554-triggers-when-both-lhs-and-rhs-is/10034931) the issue on the MSVC forums but also added the not-too-noisy fix. Once support for faulty MSVC compilers is dropped, the extra parens can safely be removed.
> Proper MSVC warning fix and note

- build/makefile
`-lrt` is only a linux thing. Removing this gave me the ability to build the benchmarks (which I will post when they are finished)
> Unlock ability to build benchmarks on OSX

- benchmarks/benchmarks.cpp
There were a number of warnings for unused, and uninitialized variables in the benchmark on OSX.
- Initialize uninitialized variables that were later passed as const reference
- Remove unused variables
- Put pragma guards around tbb, because they are using a deprecated declaration in OSX
> Get rid of warnings when compiling benchmarks

- CMakeLists.txt
Hi
Just tripped over a weird issue using Fedora's concurrentqueue package. Its generated `concurrentqueueConfigVersion.cmake` has this at the end:
```
if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "4" STREQUAL "")
return()
endif()
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "4")
math(EXPR installedBits "4 * 8")
set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```
which causes `meson` to fail to find the package using its `cmake` dependency finder, as `CMAKE_SIZEOF_VOID_P` is 8.
To remove that chunk of cmake completely, it looks like adding `ARCH_INDEPENDENT` to `write_basic_package_version_file` is the thing to do. Certainly regenerating the Fedora package with this patch removes the above and allows meson to find the package, but I avoid …
> Make cmake ARCH_INDEPENDENT

- README.md
The previous one doesn't work anymore
There is also a [full version](https://iditkeidar.com/wp-content/uploads/files/ftp/SALSA-full.pdf)
and a slitly modified version of the full verion is also available via [Technion hosting](https://ece.technion.ac.il/wp-content/uploads/2021/01/publication_807-1.pdf)
Also, maybe web archive links should be considered
> Updated SALSA article URL
